class Constant:
    SCREEN_WIDTH = 1280
    SCREEN_HEIGHT = 720
    FRAME_RATE = 60

    TILE_SIZE = 256

    GRID_WIDTH = 32
    GRID_HEIGHT = 32

    DELIVERY_TIME = 60
    DELIVERY_FINISHING_TIME = 5

    DELIVERY_SCORE_INCREASE = DELIVERY_TIME * 10

    PLAYER_SPEED = 4
    PLAYER_SPEED_GRASS_MULTIPLIER = 0.6
    PLAYER_SPEED_SLOW_WALKING_MULTIPLIER = 0.3

    MAX_ZOMBIE_SPEED = 3
