class Constant:
    SCREEN_WIDTH = 1280
    SCREEN_HEIGHT = 720
    FRAME_RATE = 60

    TILE_SIZE = 256

    GRID_WIDTH = 32
    GRID_HEIGHT = 32

    DELIVERY_TIME = 5

    PLAYER_SPEED = 6
    PLAYER_SPEED_GRASS_MULTIPLIER = 0.6
    PLAYER_SPEED_SLOW_WALKING_MULTIPLIER = 0.3
